bglobal:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.18:8080']

rule_files:
  - 'alert-rules.yml'

alerting:
  alertmanagers:
    - scheme: http
    - static_configs:
        - targets: ['192.168.1.18:9093']
